before_all do
  ensure_git_branch(
  branch: 'fastlane')
  ensure_git_status_clean
  # git_pull(rebase: true)
end

platform :android do
  private_lane :slack_message do |options|
    slack(
            slack_url: "https://hooks.slack.com/services/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",
            channel: "#react-native",
            success: true,
            message: options[:message],
            payload: { 
                "🗓 Build Date" => Time.new.to_s,
                "🌎 Environment" => ENV['ENV_NAME']
            },
            default_payloads: [:git_branch, :test_result, :last_git_commit_hash],
    )
end
  desc "Android build and release to internal testing"
    lane :internal do
        gradle(task: 'clean', project_dir: './android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
        upload_to_play_store_internal_app_sharing(package_name: 'com.test.production.app', aab: './android/app/build/outputs/bundle/release/app-release.aab')
        slack_message(message: "🎉 uploaded to Playstore Beta Successfully 🎉")
        git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
        push_to_git_remote
    end
    desc "Android build and release to beta"
    lane :beta do
        gradle(task: 'clean', project_dir: './android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
        supply(track: 'beta', aab: './android/app/build/outputs/bundle/release/app-release.aab')
        slack_message(message: "🎉 uploaded to Playstore Beta Successfully 🎉")
        git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
        push_to_git_remote
    end 
    lane :release do
        increment_version_code(app_project_dir: './android/app')
        gradle(task: 'clean', project_dir: './android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
        supply(track: 'production', aab: './android/app/build/outputs/bundle/release/app-release.aab', release_status: 'draft')
        git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
        push_to_git_remote
    end
end
